### ISSUE TITLE
I don't know what the problem is, I hope you can solve it for me

### ISSUE THREAD

**Issue by jmynihao** [D3Ext/AORT#10]
![image](https://user-images.githubusercontent.com/91512026/195752833-ac72385e-3a16-4a06-9665-e0f300b57db6.png)

**Comment by D3Ext** [comment]
I will try to fix it, however would you share which script version and OS are you using?

**Comment by jmynihao** [comment]
python 3.10.7 and windows   10

**Comment by jmynihao** [comment]
The restored version is ready to use, thank you very much

**Comment by D3Ext** [comment]
Perfect, thanks for your support!
