### ISSUE TITLE
Gitpod (Ubuntu) error

### ISSUE THREAD

**Issue by cipher387** [D3Ext/AORT#3]
Traceback (most recent call last):
  File "AORT.py", line 850, in <module>
    portScan(domain)
  File "AORT.py", line 538, in portScan
    result = sock.connect_ex((domain,port))
socket.gaierror: [Errno -2] Name or service not known

for python AORT.py -d osinme.com --portscan --wayback

**Comment by D3Ext** [comment]
You have passed "osinme.com", if the target doesn't exists it could give errors, please use real targets

**Comment by D3Ext** [comment]
I added more checks to avoid errors, thanks

**Comment by cipher387** [comment]
"You have passed "osinme.com", if the target doesn't exists it could give errors, please use real targets" - It would be great if your script would write "domain does not exist" in this case

**Comment by D3Ext** [comment]
That is exactly what I added, use the last version from source and try to pass a domain that doesn't exists or is down
