### ISSUE TITLE
I got this error while running aort on my mac monterey

### ISSUE THREAD

**Issue by f-keys** [D3Ext/AORT#4]
Traceback (most recent call last):
  File "/Users/ddd/AORT/AORT.py", line 894, in <module>
    banner()
  File "/Users/ddd/AORT/AORT.py", line 62, in banner
    internet_check = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by rudSarkar** [comment]
@f-keys did you find the solution?

**Comment by D3Ext** [comment]
@rudSarkar thanks for your comment, I hope it helps more people. I don't have a mac but it should work

**Comment by f-keys** [comment]
I was able to solve it. I edited my /etc/hosts file and added 127.0.0.1 the_name_of_my_mac.local

it works fine now. thank you
