### ISSUE TITLE
TypeError: can only concatenate str (not "TXT") to str

### ISSUE THREAD

**Issue by renanhsilva** [D3Ext/AORT#7]
Hello,

I got the instalation by github

When I try use the tool, that show me

`[+] Enumerating extra DNS information...

Traceback (most recent call last):
  File "/home/user/AORT/AORT.py", line 863, in <module>
    txt_enum(domain)
  File "/home/user/AORT/AORT.py", line 163, in txt_enum
    print(c.YELLOW + info + c.END)
TypeError: can only concatenate str (not "TXT") to str
`

I tried with other domain and reinstal the requeriments, but the error still showing

Thanks

**Comment by D3Ext** [comment]
Thanks for your comment, I think that I have spotted the bug

**Comment by renanhsilva** [comment]
You rock! It`s working, thanks

**Comment by D3Ext** [comment]
Thank you for using the tool <3
